Separate out external object files
modelica/Modelica-Compliance pull request #79
Opened 2024-08-23 12:00 UTC by HansOlsson

As a replacement for #74 

To me it makes more sense that each Modelica function includes one C-function; than each of them brings all of them requiring them to be static.

2024-08-26 13:43 UTC, henrikt-ma commented on ModelicaCompliance/Resources/Include/ExtObj.c
> +/* This file is not used anymore */
Why not remove the file instead?

2024-09-10 10:39 UTC, HansOlsson commented on ModelicaCompliance/Resources/Include/ExtObj.c
> +/* This file is not used anymore */
Now done.

2024-10-01 20:42 UTC, henrikt-ma commented on ModelicaCompliance/Resources/Include/ExtObjClose.c
> +#include <stdio.h>
Why is this included everywhere?

2024-10-01 20:48 UTC, henrikt-ma commented on ModelicaCompliance/Functions/ExternalObjects/ExternalObjectTableInFunction.mo
> +    // Note that this is a copy of ModelicaCompliance.Functions.ExternalObjects.ExternalTable
I can't see that class, did you mean this?
```suggestion
    // Note that this is a copy of ModelicaCompliance.Functions.ExternalObjects.ExternalObjectTable
```

2024-10-01 20:50 UTC, henrikt-ma requested changes
I think there was a typo in a classname, but overall it looks good.

2025-01-27 13:17 UTC, HansOlsson commented on ModelicaCompliance/Resources/Include/ExtObjClose.c
> +#include <stdio.h>
I removed the unnecessary includes as well.

2025-01-28 09:47 UTC, henrikt-ma commented on ModelicaCompliance/Resources/Include/ExtObjClose.c
> +#include <stdio.h>
Good.  Resolving.

2025-01-28 09:50 UTC, henrikt-ma approved these changes
Looks good (although I haven't taken the time to test it).

2025-01-28 10:05 UTC, merged